---
collections:
  - name: paloaltonetworks.panos
    version: 2.6.0
    source: https://automationhub.mford.io
  - name: amazon.aws
    version: 1.5.0
    source: https://automationhub.mford.io
  - name: community.aws
    version: 1.5.0
    source: https://automationhub.mford.io
  - name: servicenow.itsm
    version: 1.1.0
    source: https://automationhub.mford.io
