- name: Recursively remove the acl_reports directory
  file:
    path: "{{ working_dir }}/acl_reports"
    state: absent

- name: Create a new acl_reports directory
  file:
    path: "{{ working_dir }}/acl_reports"
    state: directory


- name: create firewall inventory report
  template:
    src: firewall_inventory.j2
    dest: "{{ working_dir }}/acl_reports/index.html"
  run_once: yes


- name: create firewall rules report
  template:
    src: current_acls.j2
    dest: "{{ working_dir }}/acl_reports/{{ hostvars[inventory_hostname]['tags']['Name'] }}.html"
  vars:
    current_rules: "{{ security_rule_output.rule_details }}"
  loop: "{{security_rule_output.rule_details}}"
  loop_control:
    label: "{{ item.rule_name }}"
  # when: security_rule_output.rule_details is defined
