# REQUIREMENTS
# pip install pan-python
# pip install pandevice
# pip install xmltodict
# ansible-galaxy install paloaltonetworks.paloaltonetworks
# https://www.bountysource.com/issues/59738537-certificate-verify-failed
#   set verify to disable in the virtual environment

---
- hosts: panos
  connection: local
  gather_facts: no
  vars:
    erase: false
  vars_files:
    - ./vars/default_vars.yml
    - ./credentials/pan_credentials.yml

  roles:
    - role: paloaltonetworks.paloaltonetworks

  tasks:

    - block:
      - name: add zone trust
        panos_zone:
          ip_address: "{{ inventory_hostname }}"
          username: "{{ PAN_USERNAME }}"
          password: "{{ PAN_PASSWORD }}"
          zone: trust
          mode: layer3
          state: present

      - name: add zone untrust
        panos_zone:
          ip_address: "{{ inventory_hostname }}"
          username: "{{ PAN_USERNAME }}"
          password: "{{ PAN_PASSWORD }}"
          zone: untrust
          mode: layer3
          state: present
      when: not erase|bool

    - block:
      - name: remove zone trust
        panos_zone:
          ip_address: "{{ inventory_hostname }}"
          username: "{{ PAN_USERNAME }}"
          password: "{{ PAN_PASSWORD }}"
          zone: trust
          mode: layer3
          state: absent

      - name: remove zone untrust
        panos_zone:
          ip_address: "{{ inventory_hostname }}"
          username: "{{ PAN_USERNAME }}"
          password: "{{ PAN_PASSWORD }}"
          zone: untrust
          mode: layer3
          state: absent
      when: erase|bool
