---
- name: Configure PANOS admin password
  hosts: panos
  gather_facts: no
  vars_files:
    - ./vars/default_vars.yml
    - ./credentials/pan_credentials.yml

  # collections:
  #   - paloaltonetworks.panos

  tasks:
    # - name: Wait for SSH to come up
    #   delegate_to: "{{ item }}"
    #   wait_for_connection:
    #     delay: 60
    #     timeout: 320
    #   loop: "{{  groups['panos'] }}"

    - name: Configure admin password
      paloaltonetworks.panos.panos_admpwd:
        ip_address: "{{ inventory_hostname }}"
        username: "admin"
        key_filename: "{{ working_dir }}/{{ ec2_prefix }}-key-private.pem"
        newpassword: "{{ PAN_PASSWORD }}"
      register: result
      until: not result|failed
      retries: 10
      delay: 30
