# REQUIREMENTS
# pip install pan-python
# pip install pandevice
# pip install xmltodict
# ansible-galaxy install paloaltonetworks.paloaltonetworks
# https://www.bountysource.com/issues/59738537-certificate-verify-failed
#   set verify to disable in the virtual environment

---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    erase: false
  vars_files:
    - ./vars/default_vars.yml
    - ./credentials/servicenow_credentials.yml
    - ./credentials/gmail_creds.yml

  # roles:
  #   - role: paloaltonetworks.paloaltonetworks

  tasks:

    - name: Create a change request in ServiceNow
      servicenow.itsm.change_request:
        state: new
        type: standard
        short_description: "Apply Palo Alto Networks Access Policies"
        requested_by: admin
        instance:
          host: "https://{{ SN_INSTANCE }}.service-now.com"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
      delegate_to: localhost
      register: request

    # - debug:
    #     var: request.record.number


    - name: Sending an email requesting approval
      mail:
        host: smtp.gmail.com
        port: 587
        username: "{{ gmail_username }}"
        password: "{{ gmail_password }}"
        to:
        - "Michael Ford <{{ approver_email }}>"
        - "{{ secondary_approver }}"
        subject: "New ServiceNow Change Request {{ request.record.number }}"
        body: "You have a new Change Request. Please click on this URL to view: https://{{ SNOW_INSTANCE }}.service-now.com/nav_to.do?uri=change_request.do?sysparm_query=number={{ new_change_request.record.number }}"
      delegate_to: localhost
