name: Publish to Ansible Galaxy

on:
  release:
    types:
      - published

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Ansible
      run: |
        pip install ansible
    - name: Create the Galaxy tarball to be published
      run: |
        ansible-galaxy collection build
    - name: Upload to Ansible Galaxy
      env:
        GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
      run: |
        ansible-galaxy collection publish --api-key ${GALAXY_API_KEY} palo*
